### ISSUE TITLE
Toggle Textures and Animations

### ISSUE THREAD

**Issue by Elitesparkle** [phoenix7700/DungeonTeleports#1]
I think it would be nice to have an option or two separate options to disable the texture that indicates if a given Portal has been unlocked and the animation that appears when mouseovering a certain Dungeon icon.

**Comment by phoenix7700** [comment]
There is an option to disable the animation in options.

**Comment by Elitesparkle** [comment]
I like that one but it's not really what I'm looking for. The idea is to either make the addon completely invisible to the user, or only show a texture when mouseovering a given Dungeon icon. If they decide to see something on mouseover, then maybe still let them choose between minimal and not.

**Comment by phoenix7700** [comment]
added option to hide known portals in v1.2
