### ISSUE TITLE
[bug] Siege of Boralus teleport not showing/working

### ISSUE THREAD

**Issue by n0proxy** [phoenix7700/DungeonTeleports#4]
I unlocked my Siege of Boralus teleport today (as well as a few others) and my dungeon panel isn't showing the addon teleport for Siege specifically. Another teleport I earned right after it appeared normally, and the teleport I earned earlier today also appeared normally. My friend who did all these dungeons with me and earned the same teleports (and uses this mod) ALSO has their Siege teleport not showing up. We're both horde characters - possible issue with Siege using the alliance-side entrance for m+ this xpac?

/reload and restarting my entire game did not fix the issue.

![CaptureSiege](https://github.com/user-attachments/assets/ac2b67f7-f3ca-4cfb-be8f-108b4d166274)

**Comment by phoenix7700** [comment]
Thanks for letting me know. I dont have this teleport unlocked myself. I'll look into it.

**Comment by n0proxy** [comment]
Seems fixed now in the newest version.

**Comment by phoenix7700** [comment]
Thanks for response. Was trying to get someone else to test because I dont have that teleport unlocked.
